name: midastouch
channels:
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- configargparse=1.4
- imageio=2.19.0
- imageio-ffmpeg=0.4.7
- matplotlib=3.5.1
- openblas-devel=0.3.2
- pip=21.2.4
- pyglet=1.5.16
- pyvista=0.34.0
- scikit-image=0.18.1
- scikit-learn=0.23.2
- tensorboard=2.9.0
- tqdm=4.64.0
- transforms3d=0.3.1
- suitesparse=5.10.1
- pip:
  - addict==2.4.0
  - antlr4-python3-runtime==4.8
  - anyio==3.5.0
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - asttokens==2.0.5
  - babel==2.10.1
  - backcall==0.2.0
  - beautifulsoup4==4.11.1
  - bleach==5.0.0
  - debugpy==1.6.0 
  - defusedxml==0.7.1
  - deprecation==2.1.0
  - dill==0.3.4
  - entrypoints==0.4
  - executing==0.8.3
  - fastjsonschema==2.15.3
  - freetype-py==2.3.0
  - gputil==1.4.0
  - hydra-core==1.1.2
  - ipykernel==6.13.0
  - ipython==8.3.0
  - ipython-genutils==0.2.0
  - ipywidgets==7.7.0
  - jedi==0.18.1
  - jinja2==3.1.2
  - json5==0.9.8
  - jsonschema==4.5.1
  - jupyter-client==7.3.1
  - jupyter-core==4.10.0
  - jupyter-packaging==0.12.0
  - jupyter-server==1.17.0
  - jupyterlab==3.4.0
  - jupyterlab-pygments==0.2.2
  - jupyterlab-server==2.13.0
  - jupyterlab-widgets==1.1.0
  - lxml==4.8.0
  - markupsafe==2.1.1
  - matplotlib-inline==0.1.3
  - mistune==0.8.4
  - nbclassic==0.3.7
  - nbclient==0.6.3
  - nbconvert==6.5.0
  - nbformat==5.4.0
  - nest-asyncio==1.5.5
  - networkx==2.2
  - ninja==1.10.2.3
  - notebook==6.4.11
  - notebook-shim==0.1.0
  - omegaconf==2.1.2
  - open3d==0.10
  - opencv-python==4.3.0.36
  - pandas==1.4.2
  - pandocfilters==1.5.0
  - parso==0.8.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow==6.2.1
  - prometheus-client==0.14.1
  - prompt-toolkit==3.0.29
  - psutil==5.9.0
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pybind11==2.9.2
  - pycollada==0.6
  - pygments==2.12.0
  - git+https://github.com/u1234x1234/pynanoflann.git@0.0.9
  - pyopengl==3.1.0
  - pyquaternion==0.9.9
  - pyrender==0.1.45
  - pyrsistent==0.18.1
  - pytz==2022.1
  - PyQt5==5.11.3                                         
  - pyvistaqt==0.9.0
  - pyzmq==22.3.0
  - qtpy==2.1.0
  - rtree==1.0.0
  - send2trash==1.8.0
  - sniffio==1.2.0
  - soupsieve==2.3.2.post1
  - stack-data==0.2.0
  - terminado==0.13.3
  - tinycss2==1.1.1
  - tomlkit==0.10.2
  - traitlets==5.1.1
  - trimesh==3.12.0
  - urdfpy==0.0.22
  - wcwidth==0.2.5
  - webencodings==0.5.1
  - websocket-client==1.3.2
  - widgetsnbextension==3.6.0
  - potpourri3d==0.0.7
  - seaborn==0.11.2
  - mesh_to_sdf==0.0.14
  - theseus-ai
  - gitpython==3.1.27
  - git+https://github.com/suddhu/tacto.git@master
  - git+https://github.com/utiasSTARS/liegroups@master
  - ffmpeg-python==0.2.0
  - yappi==1.3.6
  - digit-interface==0.2.1
  - gdown==4.5.3